name: easytobuy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0
  fluttertoast: ^7.1.8
  multi_image_picker: ^4.8.0
  path_provider: ^2.0.1
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.5.0
  dotted_border: ^2.0.0
  provider: ^5.0.0
  country_state_city_picker: ^1.2.7
  razorpay_flutter: ^1.2.5
  confetti: ^0.5.5
  expansion_tile_card: ^2.0.0
  intl: ^0.16.1
  dependencies:
  url_launcher: ^5.7.10
  smart_select: ^4.3.2
  image_picker: ^0.6.7+22
  mailto: ^2.0.0
  path: ^1.8.0
  flutter_custom_tabs: ^0.5.0
  flip_card: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: true
  image_path: "dev_assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "dev_assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/app_logo.png
    - lib/assets/images/etb.gif
    - lib/assets/images/coupon.jpg
    - lib/assets/images/coins.png
    - lib/assets/images/coin.png
    - lib/assets/images/logo.png
    - lib/assets/Categories/add.jpg
    - lib/assets/Categories/fashion.jpeg
    - lib/assets/Categories/global.jpeg
    - lib/assets/Categories/laptop.jpeg
    - lib/assets/Categories/mob_acc.jpeg
    - lib/assets/Categories/new_mob.jpeg
    - lib/assets/Categories/offers.jpeg
    - lib/assets/Categories/shoes.jpeg
    - lib/assets/Categories/used.jpeg
    - lib/assets/Categories/watch.jpeg

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
